#spring.application.name=osttra_csm_reconciliation_svc

springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/api/alert/v1/swagger/swagger-ui.html
springdoc.api-docs.path=/api/alert/v1/swagger/v3/api-docs
springdoc.swagger-ui.configUrl=/api/alert/v1/swagger/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/api/alert/v1/swagger/v3/api-docs
management.endpoints.web.base-path=/api/alert/v1/actuator

#Cognito props
cognito.client.id=${COGNITO_CLIENT_ID}
cognito.client.secret=${COGNITO_CLIENT_SECRET}
external.service.cognito.generation.enabled=true
external.service.cognito.validation.enabled=true


# Spring config properties
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:${CONFIG_SERVER_URL}/config/v1/
management.endpoints.web.exposure.include=*
spring.cloud.config.label=${ENV_LABEL}

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?serverTimezone=UTC&useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.name=csm
server.port=9191
spring.jpa.hibernate.ddl-auto=none

#CORS config
web.cors.allowed-origins = http://localhost:8090
web.cors.allowed-methods = OPTIONS,GET, POST,PUT,DELETE

route.host=http://csm-route-svc/api/account/v1
route.cacheUri=/cache/keys/status

jwt.excluded.urls=/api/reconciliation/v1/actuator/**,/api/reconciliation/v1/swagger/**

expiry.duration.jwttoken= 3600000
secret.key.jwttoken= ${JWT_SECRET_KEY}
app.security.enabled=false  # from here security not getting disabled

app.user.uid=7763153e-9b10-11ed-a8fc-0242ac120002
app.user.oid=1c725255-2668-4df8-bf26-fb709fe68277


