apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: csm-reconciliation-svc-secrets
  namespace: csm-dev-namespace
  labels:
    app: csm-reconciliation-svc
    type: backend
    application: csm
    environment: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: csm-external-secrets
    kind: SecretStore
  target:
    name: csm-reconciliation-svc-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: osttra-csm-dev-postgres-username
        #property: username #AWS Secrets Manager secret key
    - secretKey: DB_PASS
      remoteRef:
        key: osttra-csm-dev-postgres-password
        #property: username #AWS Secrets Manager secret key
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: osttra-csm-jwt-secret
    - secretKey: COGNITO_CLIENT_ID
      remoteRef:
        key: osttra-csm-dev-cognito_client_id
    - secretKey: COGNITO_CLIENT_SECRET
      remoteRef:
        key: osttra-csm-dev-cognito_client_secret