apiVersion: v1
kind: Service
metadata:
  name: csm-route-svc
  namespace: csm-qa-namespace
  labels:
    environment: qa
    application: csm
spec:
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP
  selector:
    app: csm-route-svc
  type: NodePort
